### ISSUE TITLE
 Paper

### ISSUE THREAD

**Issue by usmanasghar776** [Pratik-Barhate/question-classification#2]
Hi Pratik, thanks for sharing the code. I am a newbie in this domain,  I want to explore your system in detail. kindly if you let me know about the theoretical background of this code for better understanding the flow and working methodology.
Waiting actively for your positive response.
Thanks :)

**Comment by PratikBarhate** [comment]
@usman776  Steps/Flow of the code is mentioned with more details in `documentation` folder as mentioned in the README of the project. You can go through that and ask for specific question you want to know more about.

**Comment by usmanasghar776** [comment]
ok. I check and follow.
 Thanks.
