### ISSUE TITLE
Process the test data separately.

### ISSUE THREAD

**Issue by misrasaurabh1** [Pratik-Barhate/question-classification#4]
Currently the nlp on the test data happens at the very beginning of the flow. This means that there is no good way to test and predict over a new set of questions, other than preprocessing the whole train and test sets and then presumably retraining everything for every test example.

Can the test set preprocessing and prediction be made separate from the training preprocessing?

**Comment by PratikBarhate** [comment]
Every module has a method named "execute" which is responsible for calling all the required operations. For preprocessing it is in the file "raw_processing.py" and for NLP module it is the file "process_data.py". 

So you can make to similar functions train_execute, and test_execute which will separate the jobs and corresponding reduce the thread pool size.
